kotlin.code.style=official
android.useAndroidX=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
com.mikepenz.multiplatform.enabled=true
com.mikepenz.targets.enabled=false

kotlin.daemon.jvmargs=-Xmx8G

# Wasm
kotlin.incremental.wasm=true

# MPP
kotlin.mpp.enableCInteropCommonization=true

# Native
kotlin.native.binary.gc=cms

# Fix for iOS until everything is K2
# https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html#kotlin-compatibility
kotlin.native.cacheKind=none

# Compose Multiplatform
compose.resources.always.generate.accessors=true
org.jetbrains.compose.experimental.wasm.enabled=true
# fallback for old browsers
org.jetbrains.compose.experimental.jscanvas.enabled=true
