apiVersion: apps/v1
kind: Deployment
metadata:
  name: butler-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: butler-api-gateway
  template:
    metadata:
      labels:
        app: butler-api-gateway
    spec:
      containers:
        - name: butler-api-gateway
          image: illyan1337/butler-api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: butler-jwt-secret
                  key: JWT_SECRET
            - name: IDENTITY_API_URL
              valueFrom:
                configMapKeyRef:
                  name: butler-api-urls
                  key: IDENTITY_API_URL
            - name: CHAT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: butler-api-urls
                  key: CHAT_API_URL
