ktor:
  development: "$KTOR_DEVELOPMENT:false"
  deployment:
    port: "$PORT:8080"
  application:
    modules:
      - ai.nest.api_gateway.ApplicationKt.module
  defaultContentType: "$KTOR_DEFAULT_CONTENT_TYPE:application/json"

jwt:
  secret: "$JWT_SECRET:your_jwt_secret"
  issuer: "$JWT_ISSUER:your_jwt_issuer"
  audience: "$JWT_AUDIENCE:your_jwt_audience"
  realm: "$JWT_REALM:your_jwt_realm"

apis:
  IDENTITY_API: "$IDENTITY_API_URL:http://localhost:8081"
  CHAT_API: "$CHAT_API_URL:http://localhost:8082"
  NOTIFICATION_API: "$NOTIFICATION_API_URL:http://localhost:8083"
  LOCALIZATION_API: "$LOCALIZATION_API_URL:http://localhost:8084"


