apiVersion: apps/v1
kind: Deployment
metadata:
  name: butler-chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: butler-chat-service
  template:
    metadata:
      labels:
        app: butler-chat-service
    spec:
      containers:
        - name: butler-chat-service
          image: illyan1337/butler-chat-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.5"
              memory: "200Mi"
            limits:
              cpu: "1"
              memory: "500Mi"
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: butler-secrets
                  key: JWT_SECRET
            - name: IDENTITY_API_URL
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: IDENTITY_API_URL
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: POSTGRES_URL
            - name: DATABASE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: POSTGRES_DRIVER
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: butler-secrets
                  key: POSTGRES_PASSWORD
