apiVersion: apps/v1
kind: Deployment
metadata:
  name: butler-chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: butler-chat-service
  template:
    metadata:
      labels:
        app: butler-chat-service
    spec:
      containers:
        - name: butler-chat-service
          image: illyan1337/butler-chat-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.5"
              memory: "200Mi"
            limits:
              cpu: "1"
              memory: "500Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: POSTGRES_URL
            - name: DATABASE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: POSTGRES_DRIVER
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: butler-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: POSTGRES_DB
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: REDIS_URL
            - name: REDIS_USER
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: REDIS_USER
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: butler-secret
                  key: REDIS_PASSWORD
            - name: DEVELOPMENT
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: DEVELOPMENT
            - name: OTLP_EXPORTER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: butler-configmap
                  key: OTLP_EXPORTER_ENDPOINT
